# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63eba3d384746d9051297de723d6f75d6bcfe64bdc049ddee7b3d41a46b4714de3dda49e59e98f15c1aaaebb8075c8eb76fa75848084c99ab5f1a0c203e0cf0a

test:
  secret_key_base: 56307f24ecabfdbe2e510d41382e27c692bd2dc1da48d9b17a120355b527c7bb69e0f27b3e81f8073ba1b5e0a928b4828854782af7b5c1d28b4b6082fca8fca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
